### ISSUE TITLE
URL parameter to pre-fill the form

### ISSUE THREAD

**Issue by jhsoby** [wmde/wikidata-item-quality-evaluator#19]
A user requested that I help them add links to this tool from the sidebar in Wikidata via a user script. That should be an easy matter, but as far as I can tell, there is no URL parameter one can use to pre-fill the form with a given item (or set of items). So if I help him make a link, he would still have to copy and paste the item ID to the tool. Could such a parameter be added?

**Comment by botoxparty** [comment]
There is discussions open about this, you should expect to see this at some point in the near future :)

**Comment by lydiapintscher** [comment]
I'm closing this here in favor of the ticket we have on phabricator now: https://phabricator.wikimedia.org/T285056
